apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: kd
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  selector:
    app: discovery-server

  ports:
  - port: 8761
    targetPort: 8761

  type: ClusterIP
