apiVersion: apps/v1
kind: Deployment

metadata:
  name: workflow-service
  namespace: kd
  labels:
    app: workflow-service

spec:
  replicas: 2

  selector:
    matchLabels:
      app: workflow-service

  template:
    metadata:
      labels:
        app: workflow-service

    spec:
      containers:
        - name: workflow-service
          image: kdmodder/workflow-service:1.0.0
          imagePullPolicy: Always

          ports:
            - containerPort: 8087

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "250m"
              memory: "512Mi"

          readinessProbe:
            tcpSocket:
              port: 8087
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            tcpSocket:
              port: 8087
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
