name: Frontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Read Version
        run: |
          echo "Frontend Version:"
          cat frontend/version.txt
